import { Prompt } from '../enums/prompt';

export const promptPlaceholders: Map<Prompt, string> = new Map([
  [Prompt.FavoriteArtist, 'e.g. Gesaffelstein'],
  [Prompt.FavoriteSong, 'e.g. Firefly - Bedouin'],
  [Prompt.FavoriteRemix, 'e.g. Strobe (Lane 8 remix) - deadmau5'],
  [Prompt.FavoriteAlbum, 'e.g. Worlds - Porter Robinson'],
  [Prompt.FavoriteEP, 'e.g. Scary Monsters and Nice Sprites - Skrillex'],
  [Prompt.FavoriteCollab, 'e.g. Motion - Recondite, Henrik Schwarz'],
  [Prompt.FavoriteRecordLabel, 'e.g. Anjunadeep'],
  [Prompt.FavoriteLyrics, "e.g. How often I decide, to keep trippin' on my stars"],
  [Prompt.FirstLiveExperience, 'e.g. Electric Zoo, 2015'],
  [Prompt.FavoriteThrowbackTrack, 'e.g. The Whistle Song - Frankie Knuckles'],
  [Prompt.DreamCollab, 'e.g. Lane 8 x deadmau5'],
  [Prompt.DreamB2BSet, 'e.g. Tale Of Us x Bedouin'],
  [Prompt.GuiltyPleasureSong, 'e.g. Roses - The Chainsmokers'],
  [Prompt.MostAnticipatedArtist, 'e.g. Gesaffelstein'],
  [Prompt.BestConcert, 'e.g. Porter and Madeon on the Shelter tour'],
  [Prompt.BestFestival, 'e.g. Ultra Music Festival 2016'],
  [Prompt.BestSet, 'e.g. Lane 8, Red Rocks 2021'],
  [Prompt.BestB2BSet, 'e.g. Adam Beyer B2B Maceo Plex at Ultra Music Festival 2019'],
  [Prompt.MostUnderratedArtist, 'e.g. Rinzen'],
  [Prompt.BiggestMisconceptionAboutElectronicMusic, 'e.g. You need drugs to have a good time'],
  [Prompt.PerfectSunsetTrack, 'e.g. Nobody Seems to Care - 16BL'],
  [Prompt.SongToCheerUp, 'e.g. Little Voices - Lane 8'],
  [Prompt.LoveMostAboutElectronicMusic, 'e.g. The feeling of bass gliding through your body'],
  [Prompt.RemixBetterThanOriginal, 'e.g. I Want You (Jos & Eli remix) - Yotto'],
  [Prompt.RantAboutElectronicMusic, 'e.g. Why do people push past you at shows without saying excuse me?'],
  [Prompt.HouseOrTechno, 'e.g. Techno'],
  [Prompt.DubstepOrTrap, 'e.g. Trap'],
  [Prompt.RideRailOrHangBack, 'e.g. Hang back'],
  [Prompt.MoshOrShuffle, 'e.g. Shuffle'],
  [Prompt.AllIAskAtShow, "Don't disappear in the middle of the headline set"],
]);
