export enum Path {
  PromptSelector = 'PromptSelector',
  PromptInput = 'PromptInput',
  Events = 'Events',
  EventList = 'EventList',
  Matches = 'Matches',
  MatchList = 'MatchList',
  MatchChat = 'MatchChat',
  Profile = 'Profile',
  LocationSelect = 'LocationSelect',
  EventPrompts = 'EventPrompts',
  EventCarousel = 'EventCarousel',
  SpotifySearch = 'SpotifySearch',
  Waves = 'Waves',
  WaveList = 'WaveList',
  WaveFullUserProfile = 'WaveFullUserProfile',
}
